name: glab-compose-runner

services:
  socket:
    image: pip-socket-image

    command: podman system service --time=0 unix:///var/run/sockets/podman.sock
    volumes:
      - docker-socket:/var/run/sockets/
    privileged: true

  runner-unregister:
    # just unregister with the same name
    # this is allowed to fail
    image: docker.io/gitlab/gitlab-runner:latest
    entrypoint: bash
    command: -c "gitlab-runner unregister --all-runners || true; echo "" >  /etc/gitlab-runner/config.toml"
    volumes:
      - glab-config:/etc/gitlab-runner/
    environment:
      CI_SERVER_URL: https://gitlab.com/
      CI_SERVER_TOKEN: $GITLAB_REGISTRATION_TOKEN
      
  
  runner-register:
    depends_on:
      runner-unregister:
        condition: service_completed_successfully
    image: docker.io/gitlab/gitlab-runner:latest
    command: register --non-interactive --name $COMPOSE_PROJECT_NAME --leave-runner
    volumes:
      - glab-config:/etc/gitlab-runner/
    environment:
      CI_SERVER_URL: https://gitlab.com/
      REGISTRATION_TOKEN: $GITLAB_REGISTRATION_TOKEN
      RUNNER_EXECUTOR: docker
      DOCKER_IMAGE: alpine:latest

  image-loader:
    image: docker
    depends_on:
      socket:
        condition: service_started
    privileged: true
    entrypoint:
    command: docker load -i /buildcache/pip-socket-image.tar
    volumes:
      - ./buildcache:/buildcache
      - docker-socket:/var/run/sockets/
    environment:
      DOCKER_HOST: unix:///var/run/sockets/podman.sock

  executor:
    image: glab-scaler-image
    depends_on:
      socket:
        condition: service_started
      image-loader:
        condition: service_completed_successfully
      runner-register:
        condition: service_completed_successfully
    build: 
      context: dockerfiles/executor/
      dockerfile: Dockerfile
    privileged: true
    restart: always
    volumes:
      - ./buildcache:/buildcache
      - docker-socket:/var/run/sockets
      - glab-config:/etc/gitlab-runner/
    environment:
      COMPOSE_PROJECT_NAME: $COMPOSE_PROJECT_NAME
      DOCKER_HOST: unix:///var/run/sockets/podman.sock
      GITLAB_REGISTRATION_TOKEN: $GITLAB_REGISTRATION_TOKEN

volumes:
  docker-socket:
  glab-config: